# if dan else statemant

# IF NYA
# KONDISI
# AKSI
# nama = input("masukkan nama??")

# INI ADALAH PROGRAM IF INLINE
# if nama=="mail":print("kamu benar")
# print(f"terimakasih {nama}")

# PRGRAM IF INDENTATION

# if nama=="mail" :
#      print("kamu benar")
#      print("kamu benar")
# print(f"terimaksih {nama}")

# ELSE STATEMENT
# if nama=="mail":
#     print("keren kamu mail")
# else:
#     print("kamu bukan mail????")
# print("terimakasih")

print(10*"="+"GAME QUIZ"+10*"=")

start = input("Apa anda mau mulai? ")

if start=="ya" or start=="yes" or start=="oke":
    print("oke mari mulai!!!")
else:
    print("tolong masukan kata yang benar!!!!")

pertanyaan = input("1 + 1 = ")
if pertanyaan=="2":
    print("kamu pintarr!!!!")
else:
    print("Sayang sekali salah")
pertanyaan = input("2 + 2 = ")
if pertanyaan=="4":
    print("kamu pintarr!!!!")
else:
    print("Sayang sekali salah")
pertanyaan = input("3 + 3 = ")
if pertanyaan=="6":
    print("kamu pintarr!!!!")
else:
    print("Sayang sekali salah")
pertanyaan = input("4 + 4 = ")
if pertanyaan=="8":
    print("kamu pintarr!!!!")
else:
    print("Sayang sekali salah")
print("selamat kamu menyelesaikan quizz!!!!!")